USE [TAL_UNIVER]
GO

SELECT PULPIT.PULPIT_NAME AS Кафедра, ISNULL(TEACHER.TEACHER_NAME, '***')  As Препод
FROM TEACHER
RIGHT JOIN PULPIT ON PULPIT.PULPIT = TEACHER.PULPIT
ORDER BY PULPIT.PULPIT_NAME ASC;