USE [TMDAD_UNIVER]
GO

SELECT AUD.AUDITORIUM, [TYPE].AUDITORIUM_TYPENAME
FROM AUDITORIUM AS AUD, AUDITORIUM_TYPE AS [TYPE]
WHERE AUD.AUDITORIUM_TYPE = [TYPE].AUDITORIUM_TYPE;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';