use TAL_UNIVER

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME, SUBJECT.SUBJECT_NAME, STUDENT.NAME,
case 
when (PROGRESS.NOTE) = 6 then 'Шесть' 
when (PROGRESS.NOTE) = 7 then 'Семь' 
when (PROGRESS.NOTE) = 8 then 'Восемь' 
end  Оценка
from STUDENT 
inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP 
inner join PROFESSION on GROUPS.PROFESSION = PROFESSION.PROFESSION 
inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY 
where PROGRESS.NOTE between 6 and 8 
order by PROGRESS.NOTE desc;

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME, SUBJECT.SUBJECT_NAME, STUDENT.NAME, 
case 
when (PROGRESS.NOTE) = 6 then 'Шесть' 
when (PROGRESS.NOTE) = 7 then 'Семь' 
when (PROGRESS.NOTE) = 8 then 'Восемь' 
end  Оценка
from STUDENT 
inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP 
inner join PROFESSION on GROUPS.PROFESSION = PROFESSION.PROFESSION 
inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY 
where PROGRESS.NOTE between 6 and 8 
order by 
(case
when PROGRESS.NOTE = 7 then 1
when PROGRESS.NOTE = 8 then 2
else 3 
end	)