USE [TAL_UNIVER]
GO

---9. Разработать SELECT-запрос на основе CROSS JOIN-соединения таблиц 
--- AUDITORIUM_TYPE и AUDITORIUM, формиру-ющего результат, аналогичный результату, полученному при выполнении запроса в за-дании 1.
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM 
    INNER JOIN AUDITORIUM_TYPE
    ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
ORDER BY AUDITORIUM;


----
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM
    CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
ORDER BY AUDITORIUM;