use TAL_UNIVER

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
from FACULTY, PULPIT, PROFESSION
where PULPIT.FACULTY=FACULTY.FACULTY and PROFESSION.FACULTY=FACULTY.FACULTY
and 
PROFESSION_NAME in (select PROFESSION_NAME from PROFESSION 
where (PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%'))

--select PULPIT.FACULTY, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
--from PULPIT, PROFESSION
--where PROFESSION.FACULTY=PULPIT.FACULTY
--and 
--PROFESSION_NAME in (select PROFESSION_NAME from PROFESSION 
--where (PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%'))