use TAL_UNIVER

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
from FACULTY 
inner join PULPIT on PULPIT.FACULTY=FACULTY.FACULTY
inner join PROFESSION on PROFESSION.FACULTY=FACULTY.FACULTY
where 
PROFESSION_NAME in (select PROFESSION_NAME from PROFESSION 
where (PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%'))

--select PULPIT.FACULTY, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
--from PULPIT inner join PROFESSION on PROFESSION.FACULTY=PULPIT.FACULTY
--where PROFESSION_NAME in (select PROFESSION_NAME from PROFESSION 
--where (PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%'))