use TAL_UNIVER

select AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
from AUDITORIUM 
where AUDITORIUM_CAPACITY=(select top(1) AUDITORIUM_CAPACITY 
from AUDITORIUM where AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM.AUDITORIUM_TYPE 
order by AUDITORIUM_CAPACITY desc)